# If you wish to change these settings, override them in docker-compose.override.yml.  If that override files does not
# exist, create it.  See: https://docs.docker.com/compose/extends/

version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/opt/wrolpi_media
  app:
    depends_on:
      - api
    build:
      context: .
      dockerfile: docker/app/Dockerfile
  web:
    depends_on:
      - app
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - ${WEB_HOST-127.0.0.1}:${WEB_PORT-8080}:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./test:/opt/media"
  map_db:
    build:
      context: .
      dockerfile: docker/map_db/Dockerfile
  map:
    depends_on:
      - map_db
    build:
      context: .
      dockerfile: docker/map/Dockerfile