version: '3'
services:
  db:
    container_name: wrolpi_db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 54321:5432  # for local development
  api:
    container_name: wrolpi_api
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8080:8080  # for local development
    env:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    volumes:
      - .:/opt/wrolpi
      # Uncomment the following line and change the drive to your drive or media directory.  Change your local.yaml
      # config to match this directory.
      # - /media/8TB:/opt/wrolpi_media
  app:
    container_name: wrolpi_app
    depends_on:
      - api
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 3000:3000
    env:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    volumes:
      - './app:/app'
  map:
    container_name: wrolpi_openstreetmap
    depends_on:
      - map_db
    build:
      context: .
      dockerfile: docker/map/Dockerfile
  map_db:
    container_name: wrolpi_map_db
    build:
      context: .
      dockerfile: docker/map_db/Dockerfile
