# Development containers, these should only be used if you are developing.
version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 54321:5432
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/opt/wrolpi
    ports:
      - ${REACT_APP_API-127.0.0.1:8081}:8081
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - "./app:/app"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - ${WEB_HOST-127.0.0.1}:${WEB_PORT-8080}:80
    volumes:
      - "./nginx.dev.conf:/etc/nginx/nginx.conf"
      - "./test:/opt/media"