# If you wish to change these settings, override them in docker-compose.override.yml.  If that override files does not
# exist, create it.  See: https://docs.docker.com/compose/extends/

version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/opt/wrolpi_media
  app:
    depends_on:
      - api
    build:
      context: .
      dockerfile: docker/app/Dockerfile
  web:
    depends_on:
      - app
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - ${WEB_HOST-0.0.0.0}:${WEB_PORT-8080}:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./test:/opt/media"
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - './map.osm.pbf:/data.osm.pbf'
      - openstreetmap-data:/var/lib/postgresql/12/main
      - openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
      - "8082:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
    external: true