# If you wish to change these settings, override them in docker-compose.override.yml.  If that override files does not
# exist, create it.  See: https://docs.docker.com/compose/extends/

version: '3'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 54321:5432  # allows access for the python api when running locally
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - ${REACT_APP_API-127.0.0.1:8081}:8081
    volumes:
      - .:/opt/wrolpi
      - .:/opt/wrolpi_media
  app:
    depends_on:
      - api
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - ${APP_HOST-127.0.0.1}:${APP_PORT-5000}:5000
  nginx:
    depends_on:
      - app
      - api
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./test/example_videos:/usr/share/nginx/html"
  map_db:
    build:
      context: .
      dockerfile: docker/map_db/Dockerfile
  map:
    depends_on:
      - map_db
    build:
      context: .
      dockerfile: docker/map/Dockerfile