# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  api-tests-3.8:
    docker:
      - image: cimg/python:3.8
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: wrolpi
          POSTGRES_PASSWORD: "wrolpi"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg texlive-latex-base texlive-latex-extra
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: './venv/bin/pytest -svv wrolpi modules'
  api-tests-3.9:
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: wrolpi
          POSTGRES_PASSWORD: "wrolpi"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg texlive-latex-base texlive-latex-extra
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: './venv/bin/pytest -svv wrolpi modules'
  api-tests-3.10:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: wrolpi
          POSTGRES_PASSWORD: "wrolpi"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg texlive-latex-base texlive-latex-extra
      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: './venv/bin/pytest -svv wrolpi modules'

workflows:
  wrolpi-api-tests:
    jobs:
      - api-tests-3.8
      - api-tests-3.9
      - api-tests-3.10
