# Most of these names were decided by YT-DLP project, we pass these to any calls to that project.
continue_dl: true
dateafter: 19900101
file_name_format: "%(uploader)s_%(upload_date)s_%(id)s_%(title)s.%(ext)s"
format: 22/135/18/43
nooverwrites: true
quiet: false
writeautomaticsub: true
writeinfojson: true
writesubtitles: true
writethumbnail: true
youtube_include_dash_manifest: false
